### ISSUE TITLE
How does metadata on MIDI tracks work?

### ISSUE THREAD

**Issue by simonwiles** [broadwell/demotron#1]
What's the deal with metadata w/r/t MIDI tracks?

This code loops all the tracks and writes to a `rollMetadata` object, and so of course if there are any collisions in "Text Event" keys, the value from the last track will be kept.  Is it the case that only the first track contains such metadata?  Or is this one of those "wild west of implementations" situations?

https://github.com/broadwell/demotron/blob/dab5da76535d2b3ec6bbefaf7605ce0766f25372/src/App.js#L264-L315

You also mention at #L309 that "All of the source/performance/recording metadata is in ***this*** track as well."

**Comment by broadwell** [comment]
Thankfully there's a [SUPRA MIDI file specification](https://supra.stanford.edu/midi-spec/), which indicates that for the "expressive MIDI" files, the roll metadata and tempo changes are always (and only) on track 0, and the note events are on tracks 1 (bass register) and 2 (treble register). The latter two follow a pretty standard convention for MIDI channel assignment, though it's kind of an archaism when you're doing all of the playback in software.

This code probably could be modified to reflect the track assignments from the spec more directly, but in any case, I think we can comfortably assume that there won't be duplicate keys in the "Text Event" (meta)data.

FYI, there's not much info about the pedal events in the spec, but it turns out that the events are duplicated across both "notes" tracks (1 and 2), on the same ticks. This has potential to be troublesome given that the software players tend to collapse those tracks into a single event stream, but the `midi-player-js` module seems to handle it just fine.

**Comment by simonwiles** [comment]
Awesome, thanks, this is very helpful -- so could/should/shall we go ahead and bake the assumption into our code that track 0 is metadata, and tracks 1 and 2 are notes?

**Comment by broadwell** [comment]
Yes I think it's fine to employ these assumptions in our code. So we could for example just iterate through track 0 to get the rollMetadata and the starting tempo, then through track 1 to build the interval tree of sustain pedal events.

**Comment by simonwiles** [comment]
Cool -- that's [what I did to get the metadata](https://github.com/sul-cidr/pianolatron/commit/385f950ccef5209dc437b2cfa3d1174ec148e022), but I want to make sure I understand what I'm doing.

Cheers!
